# Generated by Django 5.0.4 on 2024-05-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambio_stock',
            old_name='ref_producto',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cambio_stock',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cambio_stock',
            name='tipo_cambio',
        ),
    ]
